// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public enum CitationType
    {
        Fact = 0,
    }

    public partial class Citation
    {
        public long CitationId { get; set; }
        public string CitationName { get; set; } = string.Empty;
        public long SourceId { get; set; }
        public string Comments { get; set; } = string.Empty;
        public string ActualText { get; set; } = string.Empty;
        public string RefNumber { get; set; } = string.Empty;
        public string Footnote { get; set; } = string.Empty;
        public byte[] ShortFootnote { get; set; } = [];
        public string Bibliography { get; set; } = string.Empty;
        public byte[] Fields { get; set; } = [];
        public DateTime ChangeDate { get; set; } = DateTime.Now;

        public virtual ICollection<Medium> Media { get; set; } = [];
        public virtual ICollection<CitationWebTag> WebTags { get; set; } = [];
        public virtual CitationLinkTable CitationDetails { get; set; } = null!;
        public virtual Source Source { get; set; } = null!;

        public override string ToString() => CitationName;

    }
}