// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Buffers.Text;
using System.Collections.Generic;

namespace rmSharp
{
    // https://sqlitetoolsforrootsmagic.com/rm9-data-dictionary/
    //Link to Primary Key of table based on OwnerType:
    //0 = PersonTable.PersonID
    //1 = FamilyTable.FamilyID
    //2 = EventTable.EventID
    //6 = TaskTable.TaskID
    //7 = NameTable.NameID
    //19 = FanTable.FanID

    public partial class CitationLinkTable
    {
        public long LinkId { get; set; }
        public long CitationId { get; set; }
        public long OwnerType { get; set; }
        public long OwnerId { get; set; }
        public long SortOrder { get; set; }
        public string Quality { get; set; } = string.Empty;
        public long IsPrivate { get; set; }
        public long Flags { get; set; }
        public DateTime ChangeDate { get; set; } = DateTime.Now;
    }

    public class PersonCitationLink : CitationLinkTable { } // OwnerID = 0
    public class FamilyCitationLink : CitationLinkTable { } // OwnerID = 1  seems unused?
    public class EventCitationLink : CitationLinkTable { }  // OwnerID = 2 
    public class NameCitationLink : CitationLinkTable { }  // OwnerID = 7 
}
