// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class ExclusionTable
    {
        public long RecId { get; set; }

        public long ExclusionType { get; set; }

        public long Id1 { get; set; }

        public long Id2 { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}