// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class MediaLinkTable
    {
        public long LinkId { get; set; }
        public long MediaId { get; set; }
        public long OwnerType { get; set; }
        public long OwnerId { get; set; }
        public long IsPrimary { get; set; }
        public long Include1 { get; set; }
        public long Include2 { get; set; }
        public long Include3 { get; set; }
        public long Include4 { get; set; }
        public long SortOrder { get; set; }
        public long RectLeft { get; set; }
        public long RectTop { get; set; }
        public long RectRight { get; set; }
        public long RectBottom { get; set; }
        public string Comments { get; set; } = string.Empty;
        public DateTime ChangeDate { get; set; }
    }

    //Link to owner based on OwnerType:
    //0 = Person
    //1 = Family
    //2 = Events
    //3 = Source
    //4 = Citation
    //5 = Place
    // ??? 6 = TaskTable.TaskID 
    //7 = NameTable.NameID
    // ??? 19 = FanTable.FanID

    public class MediaPersonLink : MediaLinkTable { } // OwnerType = 0
    public class MediaEventLink : MediaLinkTable { } // OwnerType = 2
    public class MediaSourceLink : MediaLinkTable { } // OwnerType = 3
    public class MediaCitationLink : MediaLinkTable { } // OwnerType = 4
}