// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public enum NameTypes { Primary = 0, AKA = 1, Birth = 2, Immigrant = 3, Maiden = 4, Married = 5, Nickname = 6, OtherSpelling = 7 };
    public enum Proof { unknown = 0, proven = 1, disproven = 2, disputed = 3 };

    public partial class Name
    {
        public long NameId { get; set; }
        public long OwnerId { get; set; }
        public string Surname { get; set; } = string.Empty;
        public string Given { get; set; } = string.Empty;
        public string Prefix { get; set; } = string.Empty;
        public string Suffix { get; set; } = string.Empty;

        public string Nickname { get; set; } = string.Empty;
        public NameTypes NameType { get; set; } = NameTypes.Primary;
        public string Date { get; set; } = ".";
        public long SortDate { get; set; }
        public bool IsPrimary { get; set; } = true;
        public bool IsPrivate { get; set; } = false;
        public Proof Proof { get; set; } = Proof.unknown;
        public string Sentence { get; set; } = string.Empty;
        public string Note { get; set; } = string.Empty;
        public long BirthYear { get; set; }
        public long DeathYear { get; set; }
        public long Display { get; set; }
        public string Language { get; set; } = string.Empty;
        public string SurnameMp { get; set; } = string.Empty;
        public string GivenMp { get; set; } = string.Empty;
        public string NicknameMp { get; set; } = string.Empty;
        public DateTime ChangeDate { get; set; }
        public virtual ICollection<Citation> Citations { get; set; } = [];
        public virtual ICollection<Task> Tasks { get; set; } = [];

        public override string ToString() => $"{Surname} {Given}";
    }
}