// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class SourceTemplateTable
    {
        public long TemplateId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public long Favorite { get; set; }
        public string Category { get; set; } = string.Empty;
        public string Footnote { get; set; } = string.Empty;
        public string ShortFootnote { get; set; } = string.Empty;
        public string Bibliography { get; set; } = string.Empty;
        public byte[] FieldDefs { get; set; } = [];

        public DateTime ChangeDate { get; set; }
    }
}