// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class Task
    {
        public long TaskId { get; set; }
        public long TaskType { get; set; }
        public string RefNumber { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public long Status { get; set; }
        public long Priority { get; set; }
        public string Date1 { get; set; } = string.Empty;
        public string Date2 { get; set; } = string.Empty;
        public string Date3 { get; set; } = string.Empty;
        public long SortDate1 { get; set; }
        public long SortDate2 { get; set; }
        public long SortDate3 { get; set; }
        public string Filename { get; set; } = string.Empty;
        public string Details { get; set; } = string.Empty;
        public string Results { get; set; } = string.Empty;
        public long Exclude { get; set; }
        public DateTime ChangeDate { get; set; }

        public override string ToString() => Name;
    }
}