// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{ 
    public partial class AncestryTable
    {
        public long LinkId { get; set; }

        public long? LinkType { get; set; }

        public long? RmId { get; set; }

        public string? AnId { get; set; }

        public long? Modified { get; set; }

        public string? AnVersion { get; set; }

        public double? AnDate { get; set; }

        public long? Status { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}