// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class ConfigTable
    {
        public long RecId { get; set; }

        public long? RecType { get; set; }

        public string? Title { get; set; }

        public byte[]? DataRec { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}