// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
//using Npgsql.EntityFrameworkCore.PostgreSQL.Query.Expressions.Internal;
using rmSharp;
using System;
using System.Collections.Generic;

namespace rmSharp
{
    //enum OwnerType { Person = 0, Family = 1 }

    public partial class Event
    {
        public long EventId { get; set; }
        public long EventType { get; set; }
        public long OwnerType { get; set; }
        public long OwnerId { get; set; }
        public long FamilyId { get; set; }
        public long PlaceId { get; set; }
        public long SiteId { get; set; }
        public RMDate Date { get; set; } = new RMDate();
        public long SortDate { get; set; }
        public long IsPrimary { get; set; }
        public long IsPrivate { get; set; }
        public long Proof { get; set; }
        public long Status { get; set; }
        public string Sentence { get; set; } = string.Empty;
        public string Details { get; set; } = string.Empty;
        public string Note { get; set; } = string.Empty;
        public DateTime ChangeDate { get; set; }
        public virtual FactType FactType { get; set; } = null!;

        public virtual Place? Place { get; set; }
        public virtual ICollection<Citation> Citations { get; set; } = [];
        public virtual ICollection<Medium> Media { get; set; } = [];
        public virtual ICollection<Task> Tasks { get; set; } = [];


        public override string ToString() => FactType.ToString();

    }

    public class PersonEvent : Event { }
    public class FamilyEvent : Event { }
}