// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class FamilySearchTable
    {
        public long LinkId { get; set; }

        public long? LinkType { get; set; }

        public long? RmId { get; set; }

        public string? FsId { get; set; }

        public long? Modified { get; set; }

        public string? FsVersion { get; set; }

        public double? FsDate { get; set; }

        public long? Status { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}