// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class FantypeTable
    {
        public long FantypeId { get; set; }

        public string? Name { get; set; }

        public string? Role1 { get; set; }

        public string? Role2 { get; set; }

        public string? Sentence1 { get; set; }

        public string? Sentence2 { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}