// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class Fantable
    {
        public long FanId { get; set; }

        public long? Id1 { get; set; }

        public long? Id2 { get; set; }

        public long? FanTypeId { get; set; }

        public long? PlaceId { get; set; }

        public long? SiteId { get; set; }

        public string? Date { get; set; }

        public long? SortDate { get; set; }

        public string? Description { get; set; }

        public string? Note { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}