// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    //public class Group
    //{
    //    public long Id { get; set; }
    //    public virtual ICollection<GroupEntry> Entries { get; set; } = [];
    //    public virtual PayloadGroup GroupInfo { get; set; } = null!;
    //}


    public partial class GroupEntry
    {
        public long RecId { get; set; }
        public long GroupId { get; set; }
        public long StartId { get; set; }
        public long EndId { get; set; }
        public DateTime ChangeDate { get; set; }
        public override string ToString()
        {
            return $"{StartId}-{EndId}";
        }

    }
}