// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace rmSharp
{
    public partial class GroupEntry
    {
        public long RecId { get; set; }
        public long GroupId { get; set; }
        public long StartId { get; set; }
        public long EndId { get; set; }
        // public DateTime? ChangeDate { get; set; }  // currently not used by RM
       
        public override string ToString() => $"{StartId}-{EndId}";
    }
}