// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Castle.Components.DictionaryAdapter.Xml;
using System;
using System.Collections.Generic;
using static System.Environment;
using System.IO;
using DelegateDecompiler;

namespace rmSharp
{
    public partial class Medium
    {
        public long MediaId { get; set; }
        public long MediaType { get; set; }
        public string MediaPath { get; set; } = string.Empty;
        public string MediaFile { get; set; } = string.Empty;
        public string Url { get; set; } = string.Empty;
        public byte[]? Thumbnail { get; set; } = [];
        public string Caption { get; set; } = string.Empty;
        public string RefNumber { get; set; } = string.Empty;
        public string Date { get; set; } = string.Empty;
        public long SortDate { get; set; }
        public string Description { get; set; } = string.Empty;
        public DateTime ChangeDate { get; set; }
        
        [Computed]
        public string Filename
        {
            get
            {
                var mPath = this.MediaPath;
                if (mPath[0] == '~')
                {
                    var basePath = GetFolderPath(SpecialFolder.UserProfile);
                    mPath = Path.Combine(basePath, mPath.Substring(2), MediaFile);

                }
                else if (mPath[0] == '*')
                {
                    var basePath = AppDomain.CurrentDomain.BaseDirectory;
                    mPath = Path.Combine(basePath, mPath.Substring(2), MediaFile);
                }
                else
                {
                    mPath = Path.Combine(mPath, MediaFile);
                }
                return mPath;
            }
        }
    }
}