// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class RoleTable
    {
        public long RoleId { get; set; }

        public string? RoleName { get; set; }

        public long? EventType { get; set; }

        public long? RoleType { get; set; }

        public string? Sentence { get; set; }

        public DateTime ChangeDate { get; set; }
    }
}