// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Castle.Components.DictionaryAdapter.Xml;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace rmSharp
{
    public partial class Tag
    {
        public long TagId { get; set; }
        public long TagType { get; set; }
        public long TagValue { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public DateTime ChangeDate { get; set; }
        protected internal virtual ICollection<GroupEntry> Entries { get; set; } = [];
    }

    public class Group : Tag
    {
        public Group() { }
        public Group(string name) => this.Name = name;

        public List<Person> Persons { get; set; } = [];


        internal void UpdateRanges()
        {
            Entries.Clear();

            if (Persons.Count > 0)
            {
                foreach (var entry in Persons.OrderBy(p => p.PersonId).GetIdRanges())
                {
                    Entries.Add(new GroupEntry
                    {
                        StartId = entry.startId,
                        EndId = entry.endId,
                    });
                }
            }
        }
    }
}