// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{ 
    public partial class TaskLinkTable
    {
        public long LinkId { get; set; }

        public long TaskId { get; set; }

        public long OwnerType { get; set; }

        public long OwnerId { get; set; }

        public DateTime ChangeDate { get; set; }
    }

    public class TaskPerson : TaskLinkTable { }       // OwnerID = 0
    public class TaskFamily : TaskLinkTable { }       // OwnerID = 1
    public class TaskEvent : TaskLinkTable { }        // OwnerID = 2
    public class TaskPlace : TaskLinkTable { }        // OwnerID = 5
    public class TaskName : TaskLinkTable { }         // OwnerID = 7
    public class TaskFolder : TaskLinkTable { }       // OwnerID = 18
    public class TaskAssociation : TaskLinkTable { }  // OwnerID = 19
}