// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace rmSharp
{
    public partial class WebTag
    {
        public long LinkId { get; set; }
        public long OwnerType { get; set; }
        public long OwnerId { get; set; }
        public long LinkType { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Url { get; set; } = string.Empty;
        public string Note { get; set; } = string.Empty;
        public DateTime ChangeDate { get; set; }

        public override string ToString() => Url;
    }

    public class PersonWebTag : WebTag { }; // ownerType 0
    public class SourceWebTag : WebTag { }; // ownerType 3
    public class CitationWebTag : WebTag { }; // ownerType 4
    public class PlaceWebTag : WebTag { }; // ownerType 5
    public class ResearchItemWebTag : WebTag { }; // ownerType 15

}
